services:
  # https://hub.docker.com/r/ollama/ollama
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:0.4.2 #${OLLAMA_DOCKER_TAG-latest}

# Latest releases found here: https://github.com/open-webui/open-webui/releases
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.3.35 #${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - openedai-speech
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    env_file: .env.open-webui
      
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  # Latest version found here: https://github.com/matatonic/openedai-speech/releases/tag/0.18.2
  openedai-speech:
    image: ghcr.io/matatonic/openedai-speech:0.18.2
    container_name: openedai-speech
    # env_file: .env
    environment:
      - 'TTS_HOME=voices'
      - 'HF_HOME=voices'
      - 'PRELOAD_MODEL=xtts'
    ports:  # No need to expose ports, this is a backend service
      - "8087:8000"
    volumes:
      - ./data/openedai-speech/voices:/app/voices
      - ./data/openedai-speech/config:/app/config
    # labels:
    #   - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  # https://hub.docker.com/r/cloudflare/cloudflared
  cloudflared-tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:2024.11.0
    restart: unless-stopped
    command: tunnel run
    env_file: .env.cloudflared

volumes:
  ollama: {}
  open-webui: {}
  # tts-voices: {}
  # tts-config: {}
