services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.3.5 #${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - openedai-speech
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'AUDIO_TTS_OPENAI_API_BASE_URL=http://openedai-speech:8000/v1'
      - 'WEBUI_SECRET_KEY='
      - 'AUDIO_TTS_OPENAI_API_KEY=sk-111111111'
      - 'AUDIO_TTS_MODEL=tts-1-hd'
      - 'AUDIO_TTS_VOICE=alloy'
      
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  openedai-speech:
    image: ghcr.io/matatonic/openedai-speech
    container_name: openedai-speech
    # env_file: .env
    environment:
      - 'TTS_HOME=voices'
      - 'HF_HOME=voices'
      - 'PRELOAD_MODEL=xtts'
    ports:  # No need to expose ports, this is a backend service
      - "8087:8000"
    volumes:
      - ./data/openedai-speech/voices:/app/voices
      - ./data/openedai-speech/config:/app/config
    # labels:
    #   - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
  # tts-voices: {}
  # tts-config: {}
