# regex pairs to clean the text before speaking
- - ([^.])\.$
  - \1
- - '&amp;'
  - '&'
- - '&lt;'
  - <
- - '&gt;'
  - '>'
- - '&quot;'
  - '"'
- - '&#x27;'
  - ''''
- - '&copy;'
  - '©'
- - '&reg;'
  - '®'
- - '&nbsp;'
  - ' '
- - '"'
  - ''
- - ' biases '
  - ' bias''s '
- - ex\.
  - for example
- - e\.g\.
  - for example
- - ' ESG '
  - ' E.S.G. '
- - ' FY '
  - ' F.Y. '
- - ([0-9]+)-([0-9]+)
  - \1 to \2
- - '\*\*\*'
  - '*'
- - '\*\*'
  - '*'
